### ISSUE TITLE
Tier0.5 Implementation Roadmap

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/mod-progression-system#77]
# Introduction

Patch 1.5 implemented the first full 8-piece class sets, In 1.10 a long quest series was introduced to upgrade the first set into a new, stronger version. These two sets are known as either Dungeon 1 and 2 (D1, D2) or Tier 0 and 0.5 (T0, T0.5). These sets were fairly difficult to acquire and were intended as endgame gear for non-raiders. For this guide, I'll be referring to these sets as D1 and D2 respectively.
Season of Mastery
In Season of Mastery, both Tier 0 (D1) and Tier 0.5 (D2) sets are available from launch.
Season of Mastery
World of Warcraft Classic is getting its first "Season" with Season of Mastery. Seasons will have six content phases, lasting roughly 2 months for each phase, for a total of a 12 month cadence. When the Season ends, characters will have the option to transfer to permanent Classic Era realms before the Season servers are shut down. Season of Mastery will feature faster leveling, new raid mechanics, the removal of world buffs in raids, and many other changes.

## How the Tier 0.5 Works

To begin, you'll need to get the D1 set. Each class has 3 BoE pieces (*Belt, Wrist, Gloves*). The first two, Belt and Wrist, are trash drops for all classes except Warlock, who have all 3 pieces as trash drops. Helm, Chest and Legs are all boss drops, with each dropping from the same boss for all classes. The remaining pieces drop from various bosses different to each class.

Important to note here that the D2 quests are done in segments, meaning **you do not need the full D1 set before you can start working on D2**.

During the first run of this content back in 2006, when completing the final quests of each stage where you would turn in your D1 item for the equivalent D2, if you had multiple items of the same D1 piece (for example, two Bracers), you would lose **all of them**. To be safe, store extras in your bank before doing this turn-in.

### Deliana and Mokvar

Depending on your faction, you'll be speaking to one of the two NPCs mentioned below quite frequently throughout this chain.

- [Deliana](https://classic.wowhead.com/npc=16013/deliana): located in the Great Forge (Throne room) in [Ironforge](https://classic.wowhead.com/zone=1537/ironforge) at /way 44 51
- [Mokvar](https://classic.wowhead.com/npc=16012/mokvar): located in the Valley of Wisdom (Thrall's room) in [Orgrimmar](https://classic.wowhead.com/zone=1637/orgrimmar) at /way 38 36

## Quests for Progress

Each quest will be marked with a tick if they are currently stable. (Completable and no bugs associated)

#### Part 1
- [x] [An Earnest Proposition](https://classic.wowhead.com/quest=8906/an-earnest-proposition)
- [x] [An Earnest Proposition](https://classic.wowhead.com/quest=8914/an-earnest-proposition)
[Silithus Venom Sample](https://classic.wowhead.com/item=22381/silithus-venom-sample) wrong drop chances on mobs. 80% on AC compared to 4% on classic.
[Mokvar](https://classic.wowhead.com/npc=16012/mokvar) Doesn't reward the next quest on complete.

#### Part 2

- [x] [A Supernatural Device](https://classic.wowhead.com/quest=8922/a-supernatural-device)
- [x] [A Supernatural Device](https://classic.wowhead.com/quest=8923/a-supernatural-device)
[Mux Manascrambler](https://classic.wowhead.com/npc=16014/mux-manascrambler) is missing 2 conditions on his gossip options for quest complete, to recover the lost items from his quests.
- [x] [The Ectoplasmic Distiller](https://classic.wowhead.com/quest=8921/the-ectoplasmic-distiller)
- [x] [Hunting for Ectoplasm](https://classic.wowhead.com/quest=8924/hunting-for-ectoplasm)
[Scorched Ectoplasm](https://classic.wowhead.com/item=21937/scorched-ectoplasm) wrong drop chances on mobs. 80% on AC compared to 15% on classic.
[Frozen Ectoplasm](https://classic.wowhead.com/item=21936/frozen-ectoplasm) wrong drop chances on mobs. 80% on AC compared to 15% on classic.
[Stable Ectoplasm](https://classic.wowhead.com/item=21935/stable-ectoplasm) wrong drop chances on mobs. 80% on AC compared to 15% on classic.
[Tortured Druids](https://classic.wowhead.com/npc=12178/tortured-druid) Aren't dropping Scorched Ectoplasm.
- [x] [A Portable Power Source](https://classic.wowhead.com/quest=8925/a-portable-power-source)
[Magma Lord Bokk](https://classic.wowhead.com/npc=16043/magma-lord-bokk#comments) Has 100% quest item drop chance instead of 59%.
- [x] [A Shifty Merchant](https://classic.wowhead.com/quest=8928/a-shifty-merchant)
Missing next quest reward.
- [x] [Return to Deliana](https://classic.wowhead.com/quest=8977/return-to-deliana)
- [x] [Return to Mokvar](https://classic.wowhead.com/quest=8978/return-to-mokvar)
- [x] [Just Compensation](https://classic.wowhead.com/quest=8931/just-compensation)
- [x] [Just Compensation](https://classic.wowhead.com/quest=8938/just-compensation)

#### Part 3

- [x] [In Search of Anthion](https://classic.wowhead.com/quest=8929/in-search-of-anthion)
- [x] [In Search of Anthion](https://classic.wowhead.com/quest=8930/in-search-of-anthion)
- [x] [Dead Man's Plea](https://classic.wowhead.com/quest=8945/dead-mans-plea)
- [x] [Proof of Life](https://classic.wowhead.com/quest=8946/proof-of-life)
- [x] [Anthion's Strange Request](https://classic.wowhead.com/quest=8947/anthions-strange-request)
- [x] [Anthion's Old Friend](https://classic.wowhead.com/quest=8948/anthions-old-friend)
- [x] [Falrin's Vendetta](https://classic.wowhead.com/quest=8949/falrins-vendetta)
[Ogre Warbeads](https://classic.wowhead.com/item=21982/ogre-warbeads) Wrong drop rates:

| Creature | Level | Zone | Faction | Chance count | Chance |
| --- | --- | --- | --- | --- | --- |
| Gordok Mage-Lord | 57 - 58Elite | Dire Maul | A H | 1060out of 11400 | 9 |  
| Gordok Brute | 57 - 58Elite | Dire Maul | A H | 2041out of 31956 | 6 |  
| Gordok Ogre-Mage | 52 - 53Elite | Feralas | A H | 565out of 10690 | 5 |  
| Gordok Enforcer | Elite | Feralas | A H | 146out of 3190 | 5 |  
| Gordok Mauler | 53 - 54Elite |   | A H | 172out of 4847 | 4 |  
| Gordok Warlock | 59 - 60Elite | Dire Maul | A H | 649out of 24537 | 3 |  
| Gordok Captain | 59 - 60Elite | Dire Maul | A H | 147out of 4543 | 3 |  
| Gordok Reaver | 58 - 61Elite | Dire Maul | A H | 687out of 33283 | 2 |  
| Spirestone Battle Mage | 57 - 58Elite | Blackrock Spire | A H | 86out of 6210 | 1.4 |  
| Gordok Bushwacker | Elite | Dire Maul | A H | 22out of 1597 | 1.4 |  
| Urok Doomhowl | 60Rare Elite | Blackrock Spire | A H | 6out of 430 | 1.4 |  
| Spirestone Reaver | 55 - 56Elite | Blackrock Spire | A H | 186out of 15269 | 1.2 |  
| Spirestone Enforcer | 54 - 55Elite | Blackrock Spire | A H | 165out of 14284 | 1.2 |  
| Spirestone Mystic | 55 - 56Elite | Blackrock Spire | A H | 81out of 6747 | 1.2 |  
| Spirestone Ogre Magus | 54 - 55Elite | Blackrock Spire | A H | 127out of 11442 | 1.1 |  
| Spirestone Warlord | 57 - 58Elite | Blackrock Spire | A H | 132out of 12826 | 1 |  
| Highlord Omokk | 59Elite | Blackrock Spire | A H | 24out of 2672 | 0.9 |  
| Spirestone Lord Magus | Rare Elite | Blackrock Spire | A H | 3out of 897 | 0.3 |  
| Spirestone Battle Lord | Rare Elite | Blackrock Spire | A H | 3out of 1550 | 0.19 |

- [x] [The Instigator's Enchantment](https://classic.wowhead.com/quest=8950/the-instigators-enchantment)
**Doesn't reward the next quest.**

| Creature | Chance |
| --- | --- |
| Revanchion | 11 |  
| Eldreth Wraith | 10 |  
| Eldreth Spectre | 0.5 |  
| Eldreth Spirit | 0.5 |  
| Eldreth Phantasm | 0.5 |  
| Eldreth Apparition | 0.4 |  
| Eldreth Sorcerer | 0.09 |  
| Eldreth Seether | 0.07 |

- [x] [The Challenge](https://classic.wowhead.com/quest=9015/the-challenge)
[Top Piece of Lord Valthalak's Amulet](https://classic.wowhead.com/item=22047/top-piece-of-lord-valthalaks-amulet) 100% Drop rate instead of 70%.
[Banner of Provocation](https://classic.wowhead.com/item=21986/banner-of-provocation#shared-cooldown) Casts a spell name "Banner of Provocation DND".
- [x] [Anthion's Parting Words](https://classic.wowhead.com/quest=8952/anthions-parting-words)
- [x] [Anthion's Parting Words](https://classic.wowhead.com/quest=9017/anthions-parting-words)

#### Part 4

- [x] [Bodley's Unfortunate Fate](https://classic.wowhead.com/quest=8960/bodleys-unfortunate-fate)
- [x] [Bodley's Unfortunate Fate](https://classic.wowhead.com/quest=9032/bodleys-unfortunate-fate)
[Bodley](https://classic.wowhead.com/npc=16033/bodley) Is missing his visual ghostly spell.
- [x] [Three Kings of Flame](https://classic.wowhead.com/quest=8961/three-kings-of-flame)
**Not rewarding the next quest.**
- [x] The Four Components of Importance.
These Items look like they should have around a 2% drop rate which averages 50 kills to drop 1. We should check VMangos.
[Brilliant Sword of Zealotry](https://classic.wowhead.com/item=22228/brilliant-sword-of-zealotry)
[Druidical Remains](https://classic.wowhead.com/item=22226/druidical-remains#comments)
[Starbreeze Village Relic](https://classic.wowhead.com/item=22227/starbreeze-village-relic)
[Soul Ashes of the Banished](https://classic.wowhead.com/item=22229/soul-ashes-of-the-banished)
- [x] The Left Piece of Valthalak's Amulet.
- [x] [I See Alcaz Island In Your Future...](https://classic.wowhead.com/quest=8970/i-see-alcaz-island-in-your-future)
- [x] Four more Components of Importance!
- [x] The Right Piece of Valthalak's Amulet.
- [x] [Final Preparations](https://classic.wowhead.com/quest=8994/final-preparations).
**Check the drop rates on VMangos**.
- [x] [Mea Culpa, Lord Valthalak](https://classic.wowhead.com/quest=8995/mea-culpa-lord-valthalak).
- [x] [Return to Bodley](https://classic.wowhead.com/quest=8996/return-to-bodley).
- [x] [Back to the Beginning](https://classic.wowhead.com/quest=8997/back-to-the-beginning)
- [x] [Back to the Beginning](https://classic.wowhead.com/quest=8998/back-to-the-beginning)
- [x] [Saving the Best for Last](https://classic.wowhead.com/quest=9000/saving-the-best-for-last)
- [x] [Saving the Best for Last](https://classic.wowhead.com/quest=9008/saving-the-best-for-last)

### Bosses for gear

<html>
<body>

Boss | Instance | Stable
-- | -- | --
War Master Voone | Lower BRS |  Yes
Nerub'renkan | Stratholme |  
Overlord Wyrmthalak | Lower BRS |  Yes
Darkmaster Gandling | Scholomance |  Yes
General Drakkisath | Upper BRS |  Yes
Baron Rivendare | Stratholme |  Yes
Doctor Theolen Krastinov | Scholomance |  Yes
Hearthsinger Forresten | Stratholme |  
Ras Frostwhisper | Scholomance |  Yes
The Unforgiven | Stratholme |  
Mother Smolderweb | Blackrock Spire |  Yes
Gizrul the Slavener | Lower BRS |  Yes
Ramstein the Gorger | Stratholme |  
Kirtonos the Herald | Scholomance |  Yes
Warchief Rend Blackhand | Upper BRS |  Yes
Archivist Galford | Stratholme |  Yes
Maleki the Pallid | Stratholme |  
Solakar Flamewreath | Upper BRS |  Yes
Baroness Anastari | Stratholme |  Works
Jandice Barov | Scholomance |  
Timmy the Cruel | Stratholme |  No
Balnazzar | Stratholme |  Yes
The Beast | Upper BRS |  Yes
Shadow Hunter Vosh'gajin | Lower BRS |  Yes
Rattlegore | Scholomance |  
Cannon Mastery Willey | Stratholme |  
Pyroguard Emberseer | Upper BRS |  Yes
Highlord Omokk | Lower BRS |  
Gyth | Upper BRS |  Yes

</body>
</html>

**Comment by claudiodfc** [comment]
Current issue reports:
#9109
#9101
#9110
#9111
#9113
#9153

**Comment by Shineslippers** [comment]
[Mux Manascrambler](https://wowgaming.altervista.org/aowow/?npc=16014) report https://github.com/azerothcore/azerothcore-wotlk/issues/8361
[Banner of Provocation](https://wowgaming.altervista.org/aowow/?item=21986) report https://github.com/azerothcore/azerothcore-wotlk/issues/9341
